#!/bin/sh

# Verificar si pkexec está instalado
if ! command -v pkexec > /dev/null 2>&1; then
	echo "Se requiere pkexec pero no está instalado. Instale pkexec e inténtelo de nuevo."
	exit 1
fi

pkexec python3 /usr/bin/webapps-creator-ui/webapps-creator-ui.py
